package goquality

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/shanejonas/cyclo/domain/quality"
)

func TestLocalHelpersClassifyEffectsConservatively(t *testing.T) {
	source := []byte(`package repro
var global int
func pure(x int) int { local := x; local++; return local }
func chain(x int) int { return pure(x) }
func generic[T ~int](x T) T { return x+1 }
type Box struct { Count int }
func (b Box) value() int { return b.Count }
func writes(b *Box) { b.Count++ }
func noisy() { println("hello") }
func increments() { global++ }
func recursive() { recursive() }
func mutualA() { mutualB() }
func mutualB() { mutualA() }
func unknown(callback func()) { callback() }
func PureCaller() int { return chain(1)+generic(2)+Box{}.value() }
func MutationCaller(b *Box) { writes(b) }
func IOCaller() { noisy() }
func GlobalCaller() { increments() }
func RecursiveCaller() { recursive() }
func MutualCaller() { mutualA() }
func DynamicCaller(callback func()) { unknown(callback) }
`)
	root := qualitySourceModule(t, source)
	facts, err := (Analyzer{Root: root}).Extract(context.Background(), nil)
	if err != nil {
		t.Fatal(err)
	}
	report, err := quality.Evaluate(facts, quality.DefaultConfig())
	if err != nil {
		t.Fatal(err)
	}
	for _, test := range []struct {
		name     string
		kind     quality.Kind
		complete bool
		unknown  int
	}{
		{"PureCaller", quality.None, true, 0},
		{"MutationCaller", quality.MutationEffect, true, 0},
		{"IOCaller", quality.IO, true, 0},
		{"GlobalCaller", quality.Global, true, 0},
		{"RecursiveCaller", quality.UnknownEffect, false, 1},
		{"MutualCaller", quality.UnknownEffect, false, 1},
		{"DynamicCaller", quality.UnknownEffect, false, 1},
	} {
		t.Run(test.name, func(t *testing.T) {
			result := resultNamed(t, report, test.name)
			if result.Complete != test.complete || result.UnclassifiedCalls != test.unknown {
				t.Fatalf("coverage: %+v", result)
			}
			if test.kind == quality.None {
				if len(result.Effects) != 0 || result.DensityMilli != 0 {
					t.Fatalf("pure helper falsely effectful: %+v", result)
				}
				return
			}
			if len(result.Effects) != 1 || result.Effects[0].Kind != test.kind {
				t.Fatalf("effects: %+v", result.Effects)
			}
			fact := findFunction(t, facts, test.name)
			if result.Effects[0].Line != fact.Calls[0].Line {
				t.Fatalf("evidence does not point to caller: %+v", result.Effects)
			}
		})
	}
}

func resultNamed(t *testing.T, report quality.Report, name string) quality.FunctionResult {
	t.Helper()
	for _, result := range report.Functions {
		if strings.HasSuffix(result.Name, "."+name) {
			return result
		}
	}
	t.Fatalf("missing result %s", name)
	return quality.FunctionResult{}
}

func TestHelperFactsSurviveFileSelectionAndPolicyReevaluation(t *testing.T) {
	root := qualitySourceModule(t, []byte("package repro\nfunc Caller() { hidden() }\n"))
	if err := os.WriteFile(filepath.Join(root, "helper.go"), []byte("// Code generated by fixture. DO NOT EDIT.\npackage repro\nimport \"fmt\"\nfunc hidden() { fmt.Println(1) }\n"), 0600); err != nil {
		t.Fatal(err)
	}
	facts, err := (Analyzer{Root: root}).Extract(context.Background(), []string{"input.go"})
	if err != nil {
		t.Fatal(err)
	}
	if len(facts) != 1 || len(facts[0].Helpers) != 1 {
		t.Fatalf("selection or helper body missing: %+v", facts)
	}
	report, err := quality.Evaluate(facts, quality.DefaultConfig())
	if err != nil {
		t.Fatal(err)
	}
	if report.Functions[0].Effects[0].Kind != quality.IO {
		t.Fatalf("hidden helper IO lost: %+v", report)
	}
	encoded, err := json.Marshal(facts)
	if err != nil {
		t.Fatal(err)
	}
	var restored []quality.Function
	if err := json.Unmarshal(encoded, &restored); err != nil {
		t.Fatal(err)
	}
	config := quality.DefaultConfig()
	config.Prefixes = append(config.Prefixes, quality.Prefix{Path: "fmt.Println", Kind: quality.None})
	reevaluated, err := quality.Evaluate(restored, config)
	if err != nil {
		t.Fatal(err)
	}
	if len(reevaluated.Functions[0].Effects) != 0 || !reevaluated.Functions[0].Complete {
		t.Fatalf("saved helper policy not reevaluated: %+v", reevaluated)
	}
	after, err := json.Marshal(facts)
	if err != nil || !reflect.DeepEqual(encoded, after) {
		t.Fatalf("facts mutated: %v", err)
	}
}
