package gopatterns

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"strconv"
	"strings"

	"github.com/shanejonas/cyclo/domain/patterns"
)

// applyGuardFix applies a guard_clause FixSpec: invert the if statement at
// the spec's line into a guard clause.
func applyGuardFix(spec *patterns.FixSpec, src []byte) ([]byte, error) {
	fset, f, err := parseSpec(spec, src)
	if err != nil {
		return nil, err
	}
	ifLine, err := guardIfLine(spec)
	if err != nil {
		return nil, err
	}
	target := findIfAtLine(fset, f, ifLine)
	if target == nil {
		return nil, fmt.Errorf("guard_clause: no if statement at line %d", ifLine)
	}
	edit, _, ok := guardEdit(fset, target, src)
	if !ok {
		return nil, fmt.Errorf("guard_clause: cannot fix if at line %d", ifLine)
	}
	out := applyEdits(src, []textEdit{edit})
	formatted, err := format.Source(out)
	if err != nil {
		return nil, fmt.Errorf("gofmt after guard fix: %w", err)
	}
	return formatted, nil
}

// guardIfLine extracts the if_line param from a FixSpec.
func guardIfLine(spec *patterns.FixSpec) (int, error) {
	ifLine, err := strconv.Atoi(spec.Params["if_line"])
	if err != nil {
		return 0, fmt.Errorf("guard_clause FixSpec missing if_line: %w", err)
	}
	return ifLine, nil
}

// findIfAtLine locates the if statement at the given line.
func findIfAtLine(fset *token.FileSet, f *ast.File, line int) *ast.IfStmt {
	var target *ast.IfStmt
	ast.Inspect(f, func(n ast.Node) bool {
		ifStmt, ok := n.(*ast.IfStmt)
		if !ok {
			return true
		}
		if fset.Position(ifStmt.Pos()).Line == line {
			target = ifStmt
			return false
		}
		return true
	})
	return target
}

// applyValueObjectFix applies a value_object FixSpec: extract the param
// group into a struct.
func applyValueObjectFix(spec *patterns.FixSpec, src []byte) ([]byte, error) {
	// The value fixer re-detects within the file but scoped by the spec's
	// group param. For now, delegate to the existing fixer which finds
	// the clump matching the spec's group.
	fset, f, err := parseSpec(spec, src)
	if err != nil {
		return nil, err
	}
	group := spec.Params["group"]
	if group == "" {
		return nil, fmt.Errorf("value_object FixSpec missing group")
	}
	// Use the existing fixer; it will find and fix the matching clump.
	out, _, err := FixValueObjects(fset, f, src)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// applyParameterizeFix applies a parameterize FixSpec.
func applyParameterizeFix(spec *patterns.FixSpec, src []byte) ([]byte, error) {
	fset, f, err := parseSpec(spec, src)
	if err != nil {
		return nil, err
	}
	// Delegate to existing fixer; it finds parameterizable pairs.
	out, _, err := FixParameterize(fset, f, src, nil)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// applyInterfaceFix generates a Go interface for trait_method and
// capability_set candidates. The fix emits the interface definition;
// the types already implement it implicitly.
func applyInterfaceFix(spec *patterns.FixSpec, src []byte) ([]byte, error) {
	if len(spec.Definitions) == 0 {
		return nil, fmt.Errorf("interface fixer: no definitions in FixSpec")
	}
	fset, f, err := parseSpec(spec, src)
	if err != nil {
		return nil, err
	}
	methods := collectMethodSigs(fset, f, spec.Definitions, src)
	if len(methods) == 0 {
		return nil, fmt.Errorf("interface fixer: no methods found")
	}
	ifaceName := interfaceNameFor(spec.Kind)
	return insertAfterImports(fset, f, src, buildInterface(ifaceName, spec.Kind, methods)), nil
}

// collectMethodSigs extracts unique method signatures from definitions.
func collectMethodSigs(fset *token.FileSet, f *ast.File, defs []string, src []byte) []string {
	var methods []string
	seen := make(map[string]bool)
	for _, def := range defs {
		sig := methodSigFromDef(fset, f, def, src, seen)
		if sig != "" {
			methods = append(methods, sig)
		}
	}
	return methods
}

// methodSigFromDef parses a "path:line:name" definition and returns the
// method signature, or "" if it can't be found or was already seen.
func methodSigFromDef(fset *token.FileSet, f *ast.File, def string, src []byte, seen map[string]bool) string {
	parts := strings.SplitN(def, ":", 3)
	if len(parts) != 3 {
		return ""
	}
	line, err := strconv.Atoi(parts[1])
	if err != nil {
		return ""
	}
	name := parts[2]
	if seen[name] {
		return ""
	}
	seen[name] = true
	return findMethodSig(fset, f, line, name, src)
}

// interfaceNameFor returns the generated interface name for a kind.
func interfaceNameFor(kind patterns.CandidateKind) string {
	if kind == patterns.CapabilitySet {
		return "Capabilities"
	}
	return "Trait"
}

// buildInterface renders the interface definition.
func buildInterface(name string, kind patterns.CandidateKind, methods []string) []byte {
	var buf bytes.Buffer
	buf.WriteString(fmt.Sprintf("\n// %s is generated by cyclo fix from a %s candidate.\n", name, kind))
	buf.WriteString(fmt.Sprintf("type %s interface {\n", name))
	for _, m := range methods {
		buf.WriteString("\t" + m + "\n")
	}
	buf.WriteString("}\n")
	return buf.Bytes()
}

// findMethodSig finds the method at line and returns its signature
// as "Name(params) results".
func findMethodSig(fset *token.FileSet, f *ast.File, line int, name string, src []byte) string {
	fn := findFuncDecl(fset, f, line, name)
	if fn == nil {
		return ""
	}
	var buf bytes.Buffer
	buf.WriteString(name)
	buf.WriteString("(")
	buf.WriteString(renderParams(fset, fn.Type.Params, src))
	buf.WriteString(")")
	if fn.Type.Results != nil {
		buf.WriteString(" ")
		buf.WriteString(renderResults(fset, fn.Type.Results, src))
	}
	return buf.String()
}

// findFuncDecl locates the FuncDecl with the given name at the given line.
func findFuncDecl(fset *token.FileSet, f *ast.File, line int, name string) *ast.FuncDecl {
	var found *ast.FuncDecl
	ast.Inspect(f, func(n ast.Node) bool {
		fn, ok := n.(*ast.FuncDecl)
		if !ok || fn.Name.Name != name {
			return true
		}
		if fset.Position(fn.Pos()).Line != line {
			return true
		}
		found = fn
		return false
	})
	return found
}

// renderParams renders a FieldList of params as "a int, b string".
func renderParams(fset *token.FileSet, params *ast.FieldList, src []byte) string {
	if params == nil {
		return ""
	}
	var buf bytes.Buffer
	for i, p := range params.List {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString(renderFieldNames(p.Names))
		if len(p.Names) > 0 {
			buf.WriteString(" ")
		}
		buf.WriteString(exprToString(fset, p.Type, src))
	}
	return buf.String()
}

// renderFieldNames joins field names with ", ".
func renderFieldNames(names []*ast.Ident) string {
	var buf bytes.Buffer
	for j, n := range names {
		if j > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString(n.Name)
	}
	return buf.String()
}

// renderResults renders a FieldList of results as "int" or "(int, error)".
func renderResults(fset *token.FileSet, results *ast.FieldList, src []byte) string {
	if len(results.List) == 1 && len(results.List[0].Names) == 0 {
		return exprToString(fset, results.List[0].Type, src)
	}
	var buf bytes.Buffer
	buf.WriteString("(")
	for i, r := range results.List {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString(exprToString(fset, r.Type, src))
	}
	buf.WriteString(")")
	return buf.String()
}

// exprToString renders an AST expression as source text.
func exprToString(fset *token.FileSet, e ast.Expr, src []byte) string {
	start := fset.Position(e.Pos()).Offset
	end := fset.Position(e.End()).Offset
	if start < 0 || end > len(src) || start >= end {
		return ""
	}
	return string(src[start:end])
}

// insertAfterImports inserts text after the package clause and imports.
// fset is needed to convert token.Pos to byte offsets.
func insertAfterImports(fset *token.FileSet, f *ast.File, src []byte, text []byte) []byte {
	offset := importEndOffset(fset, f, src)
	out := make([]byte, 0, len(src)+len(text))
	out = append(out, src[:offset]...)
	out = append(out, text...)
	out = append(out, src[offset:]...)
	return out
}

// importEndOffset returns the byte offset after the last import,
// or after the package clause if there are no imports.
func importEndOffset(fset *token.FileSet, f *ast.File, src []byte) int {
	if pos := lastImportEnd(f, f.Imports); pos != 0 {
		return fset.Position(pos).Offset
	}
	return packageEndOffset(fset, f, src)
}

// lastImportEnd finds the end position of the GenDecl containing the last import.
func lastImportEnd(f *ast.File, imports []*ast.ImportSpec) token.Pos {
	if len(imports) == 0 {
		return 0
	}
	last := imports[len(imports)-1]
	for _, decl := range f.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}
		if genContainsImport(gen, last) {
			return gen.End()
		}
	}
	return 0
}

// genContainsImport reports whether gen declares the given import.
func genContainsImport(gen *ast.GenDecl, target *ast.ImportSpec) bool {
	for _, spec := range gen.Specs {
		if imp, ok := spec.(*ast.ImportSpec); ok && imp == target {
			return true
		}
	}
	return false
}

// packageEndOffset returns the offset after the package clause newline.
func packageEndOffset(fset *token.FileSet, f *ast.File, src []byte) int {
	offset := fset.Position(f.Name.End()).Offset
	for offset < len(src) && src[offset] != '\n' {
		offset++
	}
	return offset + 1
}



// applyAnemicModelFix applies an anemic_model FixSpec.
func applyAnemicModelFix(spec *patterns.FixSpec, src []byte) ([]byte, error) {
	fset, f, err := parseSpec(spec, src)
	if err != nil {
		return nil, err
	}
	out, _, err := FixAnemicModels(fset, f, src)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// applyPrimitiveObsessionFix applies a primitive_obsession FixSpec.
func applyPrimitiveObsessionFix(spec *patterns.FixSpec, src []byte) ([]byte, error) {
	fset, f, err := parseSpec(spec, src)
	if err != nil {
		return nil, err
	}
	out, _, err := FixPrimitiveObsession(fset, f, src)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// applyEntityIdentityFix applies an entity_identity FixSpec: replaces
// attribute-based equality (a.Name == b.Name && a.Email == b.Email) with
// identity comparison (a.ID == b.ID).
func applyEntityIdentityFix(spec *patterns.FixSpec, src []byte) ([]byte, error) {
	fset, f, err := parseSpec(spec, src)
	if err != nil {
		return nil, err
	}
	params, err := parseEntityFixParams(spec)
	if err != nil {
		return nil, err
	}
	target := findComparisonAtLine(fset, f, params.line)
	if target == nil {
		return nil, fmt.Errorf("entity_identity: no comparison at line %d", params.line)
	}
	replacement := []byte(fmt.Sprintf("%s.%s == %s.%s", params.left, params.idField, params.right, params.idField))
	start := fset.Position(target.Pos()).Offset
	end := fset.Position(target.End()).Offset
	edit := textEdit{start: start, end: end, replacement: replacement}
	out := applyEdits(src, []textEdit{edit})
	formatted, err := format.Source(out)
	if err != nil {
		return nil, fmt.Errorf("gofmt after entity_identity fix: %w", err)
	}
	return formatted, nil
}

// entityFixParams extracts and validates entity_identity FixSpec params.
type entityFixParams struct {
	line    int
	idField string
	left    string
	right   string
}

func parseEntityFixParams(spec *patterns.FixSpec) (entityFixParams, error) {
	line, err := strconv.Atoi(spec.Params["line"])
	if err != nil {
		return entityFixParams{}, fmt.Errorf("entity_identity FixSpec missing line: %w", err)
	}
	idField := spec.Params["id_field"]
	left := spec.Params["left"]
	right := spec.Params["right"]
	if idField == "" || left == "" || right == "" {
		return entityFixParams{}, fmt.Errorf("entity_identity FixSpec missing params")
	}
	return entityFixParams{line: line, idField: idField, left: left, right: right}, nil
}

// findComparisonAtLine locates a boolean comparison expression at the given line.
func findComparisonAtLine(fset *token.FileSet, f *ast.File, line int) ast.Expr {
	var target ast.Expr
	ast.Inspect(f, func(n ast.Node) bool {
		var expr ast.Expr
		switch node := n.(type) {
		case *ast.IfStmt:
			expr = node.Cond
		case *ast.ReturnStmt:
			if len(node.Results) == 1 {
				expr = node.Results[0]
			}
		}
		if expr == nil {
			return true
		}
		if fset.Position(expr.Pos()).Line == line {
			target = expr
			return false
		}
		return true
	})
	return target
}

// applyMissingIdentityFix applies a missing_identity FixSpec: adds an
// ID field to the struct.
func applyMissingIdentityFix(spec *patterns.FixSpec, src []byte) ([]byte, error) {
	fset, f, err := parseSpec(spec, src)
	if err != nil {
		return nil, err
	}
	typeName := spec.Params["type"]
	if typeName == "" {
		return nil, fmt.Errorf("missing_identity FixSpec missing type")
	}
	insertPos, err := structInsertPos(fset, f, typeName)
	if err != nil {
		return nil, err
	}
	edit := textEdit{
		start:       insertPos,
		end:         insertPos,
		replacement: []byte("\n\tID string `json:\"id\"`"),
	}
	out := applyEdits(src, []textEdit{edit})
	formatted, err := format.Source(out)
	if err != nil {
		return nil, fmt.Errorf("gofmt after missing_identity fix: %w", err)
	}
	return formatted, nil
}

// structInsertPos finds the byte offset after the last field of a struct.
func structInsertPos(fset *token.FileSet, f *ast.File, typeName string) (int, error) {
	target := findStructDecl(f, typeName)
	if target == nil {
		return 0, fmt.Errorf("missing_identity: no struct %q found", typeName)
	}
	st, ok := target.Type.(*ast.StructType)
	if !ok {
		return 0, fmt.Errorf("missing_identity: %q is not a struct", typeName)
	}
	if st.Fields == nil || len(st.Fields.List) == 0 {
		return 0, fmt.Errorf("missing_identity: struct %q has no fields", typeName)
	}
	lastField := st.Fields.List[len(st.Fields.List)-1]
	return fset.Position(lastField.End()).Offset, nil
}

// findStructDecl locates the type declaration for the named struct.
func findStructDecl(f *ast.File, typeName string) *ast.TypeSpec {
	var target *ast.TypeSpec
	ast.Inspect(f, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok {
			return true
		}
		if ts.Name.Name == typeName {
			target = ts
			return false
		}
		return true
	})
	return target
}

// applyFactoryFix applies a factory FixSpec: extracts a NewT factory
// function for a struct type built with 5+ fields in multiple places,
// and rewrites full composite literals to factory calls.
func applyFactoryFix(spec *patterns.FixSpec, src []byte) ([]byte, error) {
	typeName := spec.Params["type"]
	if typeName == "" {
		return nil, fmt.Errorf("factory: FixSpec missing type")
	}
	fset, f, err := parseSpec(spec, src)
	if err != nil {
		return nil, err
	}
	ctx, ok := newFactoryContext(fset, f, src, typeName)
	if !ok {
		return src, nil
	}
	edits := factoryEdits(ctx)
	out := applyEdits(src, edits)
	formatted, err := format.Source(out)
	if err != nil {
		return nil, fmt.Errorf("gofmt after factory fix: %w", err)
	}
	return formatted, nil
}

// factoryContext carries everything the factory fix needs: the struct
// fields, the literal rewrites, and where to insert the factory.
type factoryContext struct {
	fset        *token.FileSet
	src         []byte
	typeName    string
	factoryName string
	fields      []factoryField
	rewrites    []textEdit
	typeEnd     int
}

// newFactoryContext builds the fix context, or false when the fix should
// be skipped.
func newFactoryContext(fset *token.FileSet, f *ast.File, src []byte, typeName string) (factoryContext, bool) {
	fields, typeEnd, ok := factoryStructFields(fset, f, src, typeName)
	if !ok {
		return factoryContext{}, false
	}
	factoryName := "New" + typeName
	if hasFuncDecl(f, factoryName) {
		return factoryContext{}, false
	}
	rewrites := factoryLitRewrites(fset, f, src, typeName, factoryName, fields)
	if len(rewrites) == 0 {
		return factoryContext{}, false
	}
	return factoryContext{
		fset: fset, src: src, typeName: typeName,
		factoryName: factoryName, fields: fields,
		rewrites: rewrites, typeEnd: typeEnd,
	}, true
}

// litRewriteCtx carries the parameters for literal rewrite helpers.
type litRewriteCtx struct {
	fset        *token.FileSet
	src         []byte
	typeName    string
	factoryName string
	fields      []factoryField
}

// factoryEdits combines the literal rewrites with the factory insertion.
func factoryEdits(ctx factoryContext) []textEdit {
	edits := make([]textEdit, 0, len(ctx.rewrites)+1)
	edits = append(edits, ctx.rewrites...)
	edits = append(edits, textEdit{
		start:       ctx.typeEnd,
		end:         ctx.typeEnd,
		replacement: []byte("\n" + factoryFuncText(ctx.factoryName, ctx.typeName, ctx.fields)),
	})
	return edits
}

// factoryField is one struct field in declaration order.
type factoryField struct {
	name     string
	typeText string
}

// factoryStructFields returns the struct's fields in declaration order and
// the end offset of the type declaration. It skips generic structs,
// embedded fields, and multi-name field lines.
func factoryStructFields(fset *token.FileSet, f *ast.File, src []byte, typeName string) ([]factoryField, int, bool) {
	for _, decl := range f.Decls {
		if fields, end, ok := typeDeclFields(fset, decl, src, typeName); ok {
			return fields, end, true
		}
	}
	return nil, 0, false
}

// typeDeclFields extracts struct fields from a type declaration if it
// declares typeName as a non-generic struct with named fields.
func typeDeclFields(fset *token.FileSet, decl ast.Decl, src []byte, typeName string) ([]factoryField, int, bool) {
	gen, ok := decl.(*ast.GenDecl)
	if !ok || gen.Tok != token.TYPE {
		return nil, 0, false
	}
	for _, s := range gen.Specs {
		if fields, end, ok := typeSpecFields(fset, gen, s, src, typeName); ok {
			return fields, end, true
		}
	}
	return nil, 0, false
}

// typeSpecFields extracts fields from one type spec.
func typeSpecFields(fset *token.FileSet, gen *ast.GenDecl, s ast.Spec, src []byte, typeName string) ([]factoryField, int, bool) {
	ts, ok := matchingTypeSpec(s, typeName)
	if !ok {
		return nil, 0, false
	}
	fields := structFieldList(fset, src, ts)
	if len(fields) == 0 {
		return nil, 0, false
	}
	return fields, fset.Position(gen.End()).Offset, true
}

// matchingTypeSpec returns the type spec if it declares typeName as a
// non-generic struct.
func matchingTypeSpec(s ast.Spec, typeName string) (*ast.StructType, bool) {
	ts, ok := s.(*ast.TypeSpec)
	if !ok || ts.Name.Name != typeName || ts.TypeParams != nil {
		return nil, false
	}
	st, ok := ts.Type.(*ast.StructType)
	if !ok || st.Fields == nil {
		return nil, false
	}
	return st, true
}

// structFieldList converts struct field AST to factoryFields, skipping
// embedded or multi-name fields.
func structFieldList(fset *token.FileSet, src []byte, st *ast.StructType) []factoryField {
	var fields []factoryField
	for _, fld := range st.Fields.List {
		if len(fld.Names) != 1 {
			return nil
		}
		start := fset.Position(fld.Type.Pos()).Offset
		end := fset.Position(fld.Type.End()).Offset
		fields = append(fields, factoryField{
			name:     fld.Names[0].Name,
			typeText: string(src[start:end]),
		})
	}
	return fields
}

// hasFuncDecl reports whether f declares a function with the given name.
func hasFuncDecl(f *ast.File, name string) bool {
	found := false
	ast.Inspect(f, func(n ast.Node) bool {
		if fd, ok := n.(*ast.FuncDecl); ok && fd.Name.Name == name {
			found = true
			return false
		}
		return true
	})
	return found
}

// factoryLitRewrites finds composite literals of typeName that set every
// field and returns text edits rewriting them to factory calls.
func factoryLitRewrites(fset *token.FileSet, f *ast.File, src []byte, typeName, factoryName string, fields []factoryField) []textEdit {
	rc := litRewriteCtx{fset: fset, src: src, typeName: typeName, factoryName: factoryName, fields: fields}
	var edits []textEdit
	ast.Inspect(f, func(n ast.Node) bool {
		if edit, ok, skip := unaryLitEdit(rc, n); ok || skip {
			if ok {
				edits = append(edits, edit)
			}
			return !skip
		}
		if edit, ok := plainLitEdit(rc, n); ok {
			edits = append(edits, edit)
		}
		return true
	})
	return edits
}

// unaryLitEdit rewrites &T{...} to &NewT(...). skip is true when n was a
// &T{...} unary (handled or not) so the walker does not descend into it.
func unaryLitEdit(rc litRewriteCtx, n ast.Node) (textEdit, bool, bool) {
	ue, ok := n.(*ast.UnaryExpr)
	if !ok || ue.Op != token.AND {
		return textEdit{}, false, false
	}
	lit, ok := ue.X.(*ast.CompositeLit)
	if !ok || !isTargetLit(lit, rc.typeName) {
		return textEdit{}, false, false
	}
	args, ok := litArgs(rc.fset, rc.src, lit, rc.fields)
	if !ok {
		return textEdit{}, false, true
	}
	return textEdit{
		start:       rc.fset.Position(ue.Pos()).Offset,
		end:         rc.fset.Position(ue.End()).Offset,
		replacement: []byte("&" + rc.factoryName + "(" + args + ")"),
	}, true, true
}

// plainLitEdit rewrites T{...} to NewT(...).
func plainLitEdit(rc litRewriteCtx, n ast.Node) (textEdit, bool) {
	lit, ok := n.(*ast.CompositeLit)
	if !ok || !isTargetLit(lit, rc.typeName) {
		return textEdit{}, false
	}
	args, ok := litArgs(rc.fset, rc.src, lit, rc.fields)
	if !ok {
		return textEdit{}, false
	}
	return textEdit{
		start:       rc.fset.Position(lit.Pos()).Offset,
		end:         rc.fset.Position(lit.End()).Offset,
		replacement: []byte(rc.factoryName + "(" + args + ")"),
	}, true
}

// isTargetLit reports whether lit is a composite literal of typeName.
// Only unqualified identifiers match: the type is declared in this file.
func isTargetLit(lit *ast.CompositeLit, typeName string) bool {
	id, ok := lit.Type.(*ast.Ident)
	return ok && id.Name == typeName
}

// litArgs builds the factory call arguments in field-declaration order.
// It returns false unless the literal sets every field.
func litArgs(fset *token.FileSet, src []byte, lit *ast.CompositeLit, fields []factoryField) (string, bool) {
	if isKeyedLit(lit) {
		return keyedLitArgs(fset, src, lit, fields)
	}
	if len(lit.Elts) != len(fields) {
		return "", false
	}
	parts := make([]string, 0, len(lit.Elts))
	for _, e := range lit.Elts {
		parts = append(parts, srcText(fset, e, src))
	}
	return strings.Join(parts, ", "), true
}

// isKeyedLit reports whether the literal uses field: value form.
func isKeyedLit(lit *ast.CompositeLit) bool {
	for _, e := range lit.Elts {
		if _, ok := e.(*ast.KeyValueExpr); ok {
			return true
		}
	}
	return false
}

// keyedLitArgs builds args from a keyed literal; all fields must be set.
func keyedLitArgs(fset *token.FileSet, src []byte, lit *ast.CompositeLit, fields []factoryField) (string, bool) {
	vals := map[string]string{}
	for _, e := range lit.Elts {
		kv, ok := e.(*ast.KeyValueExpr)
		if !ok {
			return "", false
		}
		key, ok := kv.Key.(*ast.Ident)
		if !ok {
			return "", false
		}
		vals[key.Name] = srcText(fset, kv.Value, src)
	}
	parts := make([]string, 0, len(fields))
	for _, fld := range fields {
		v, ok := vals[fld.name]
		if !ok {
			return "", false
		}
		parts = append(parts, v)
	}
	return strings.Join(parts, ", "), true
}

// factoryFuncText builds the factory function source.
func factoryFuncText(factoryName, typeName string, fields []factoryField) string {
	params := make([]string, 0, len(fields))
	assigns := make([]string, 0, len(fields))
	used := map[string]bool{}
	for _, fld := range fields {
		pn := paramName(fld.name, used)
		used[pn] = true
		params = append(params, pn+" "+fld.typeText)
		assigns = append(assigns, fld.name+": "+pn)
	}
	return fmt.Sprintf("func %s(%s) %s {\n\treturn %s{%s}\n}\n",
		factoryName, strings.Join(params, ", "), typeName,
		typeName, strings.Join(assigns, ", "))
}

// paramName converts a field name to a parameter name, avoiding keywords
// and collisions.
func paramName(field string, used map[string]bool) string {
	base := lowerFirst(field)
	if isGoKeyword(base) {
		base += "Arg"
	}
	name := base
	for i := 2; used[name]; i++ {
		name = fmt.Sprintf("%s%d", base, i)
	}
	return name
}

// isGoKeyword reports whether s is a Go keyword.
func isGoKeyword(s string) bool {
	switch s {
	case "break", "case", "chan", "const", "continue", "default",
		"defer", "else", "fallthrough", "for", "func", "go", "goto",
		"if", "import", "interface", "map", "package", "range",
		"return", "select", "struct", "switch", "type", "var":
		return true
	}
	return false
}
