package gopatterns

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/token"
	"strconv"
	"strings"

	"github.com/shanejonas/cyclo/domain/patterns"
)

// applyGuardFix applies a guard_clause FixSpec: invert the if statement at
// the spec's line into a guard clause.
func applyGuardFix(spec *patterns.FixSpec, src []byte) ([]byte, error) {
	fset, f, err := parseSpec(spec, src)
	if err != nil {
		return nil, err
	}
	ifLine, err := guardIfLine(spec)
	if err != nil {
		return nil, err
	}
	target := findIfAtLine(fset, f, ifLine)
	if target == nil {
		return nil, fmt.Errorf("guard_clause: no if statement at line %d", ifLine)
	}
	edit, _, ok := guardEdit(fset, target, src)
	if !ok {
		return nil, fmt.Errorf("guard_clause: cannot fix if at line %d", ifLine)
	}
	return applyEdits(src, []textEdit{edit}), nil
}

// guardIfLine extracts the if_line param from a FixSpec.
func guardIfLine(spec *patterns.FixSpec) (int, error) {
	ifLine, err := strconv.Atoi(spec.Params["if_line"])
	if err != nil {
		return 0, fmt.Errorf("guard_clause FixSpec missing if_line: %w", err)
	}
	return ifLine, nil
}

// findIfAtLine locates the if statement at the given line.
func findIfAtLine(fset *token.FileSet, f *ast.File, line int) *ast.IfStmt {
	var target *ast.IfStmt
	ast.Inspect(f, func(n ast.Node) bool {
		ifStmt, ok := n.(*ast.IfStmt)
		if !ok {
			return true
		}
		if fset.Position(ifStmt.Pos()).Line == line {
			target = ifStmt
			return false
		}
		return true
	})
	return target
}

// applyValueObjectFix applies a value_object FixSpec: extract the param
// group into a struct.
func applyValueObjectFix(spec *patterns.FixSpec, src []byte) ([]byte, error) {
	// The value fixer re-detects within the file but scoped by the spec's
	// group param. For now, delegate to the existing fixer which finds
	// the clump matching the spec's group.
	fset, f, err := parseSpec(spec, src)
	if err != nil {
		return nil, err
	}
	group := spec.Params["group"]
	if group == "" {
		return nil, fmt.Errorf("value_object FixSpec missing group")
	}
	// Use the existing fixer; it will find and fix the matching clump.
	out, _, err := FixValueObjects(fset, f, src)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// applyParameterizeFix applies a parameterize FixSpec.
func applyParameterizeFix(spec *patterns.FixSpec, src []byte) ([]byte, error) {
	fset, f, err := parseSpec(spec, src)
	if err != nil {
		return nil, err
	}
	// Delegate to existing fixer; it finds parameterizable pairs.
	out, _, err := FixParameterize(fset, f, src, nil)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// applyInterfaceFix generates a Go interface for trait_method and
// capability_set candidates. The fix emits the interface definition;
// the types already implement it implicitly.
func applyInterfaceFix(spec *patterns.FixSpec, src []byte) ([]byte, error) {
	if len(spec.Definitions) == 0 {
		return nil, fmt.Errorf("interface fixer: no definitions in FixSpec")
	}
	fset, f, err := parseSpec(spec, src)
	if err != nil {
		return nil, err
	}
	methods := collectMethodSigs(fset, f, spec.Definitions, src)
	if len(methods) == 0 {
		return nil, fmt.Errorf("interface fixer: no methods found")
	}
	ifaceName := interfaceNameFor(spec.Kind)
	return insertAfterImports(fset, f, src, buildInterface(ifaceName, spec.Kind, methods)), nil
}

// collectMethodSigs extracts unique method signatures from definitions.
func collectMethodSigs(fset *token.FileSet, f *ast.File, defs []string, src []byte) []string {
	var methods []string
	seen := make(map[string]bool)
	for _, def := range defs {
		sig := methodSigFromDef(fset, f, def, src, seen)
		if sig != "" {
			methods = append(methods, sig)
		}
	}
	return methods
}

// methodSigFromDef parses a "path:line:name" definition and returns the
// method signature, or "" if it can't be found or was already seen.
func methodSigFromDef(fset *token.FileSet, f *ast.File, def string, src []byte, seen map[string]bool) string {
	parts := strings.SplitN(def, ":", 3)
	if len(parts) != 3 {
		return ""
	}
	line, err := strconv.Atoi(parts[1])
	if err != nil {
		return ""
	}
	name := parts[2]
	if seen[name] {
		return ""
	}
	seen[name] = true
	return findMethodSig(fset, f, line, name, src)
}

// interfaceNameFor returns the generated interface name for a kind.
func interfaceNameFor(kind patterns.CandidateKind) string {
	if kind == patterns.CapabilitySet {
		return "Capabilities"
	}
	return "Trait"
}

// buildInterface renders the interface definition.
func buildInterface(name string, kind patterns.CandidateKind, methods []string) []byte {
	var buf bytes.Buffer
	buf.WriteString(fmt.Sprintf("\n// %s is generated by cyclo fix from a %s candidate.\n", name, kind))
	buf.WriteString(fmt.Sprintf("type %s interface {\n", name))
	for _, m := range methods {
		buf.WriteString("\t" + m + "\n")
	}
	buf.WriteString("}\n")
	return buf.Bytes()
}

// findMethodSig finds the method at line and returns its signature
// as "Name(params) results".
func findMethodSig(fset *token.FileSet, f *ast.File, line int, name string, src []byte) string {
	fn := findFuncDecl(fset, f, line, name)
	if fn == nil {
		return ""
	}
	var buf bytes.Buffer
	buf.WriteString(name)
	buf.WriteString("(")
	buf.WriteString(renderParams(fset, fn.Type.Params, src))
	buf.WriteString(")")
	if fn.Type.Results != nil {
		buf.WriteString(" ")
		buf.WriteString(renderResults(fset, fn.Type.Results, src))
	}
	return buf.String()
}

// findFuncDecl locates the FuncDecl with the given name at the given line.
func findFuncDecl(fset *token.FileSet, f *ast.File, line int, name string) *ast.FuncDecl {
	var found *ast.FuncDecl
	ast.Inspect(f, func(n ast.Node) bool {
		fn, ok := n.(*ast.FuncDecl)
		if !ok || fn.Name.Name != name {
			return true
		}
		if fset.Position(fn.Pos()).Line != line {
			return true
		}
		found = fn
		return false
	})
	return found
}

// renderParams renders a FieldList of params as "a int, b string".
func renderParams(fset *token.FileSet, params *ast.FieldList, src []byte) string {
	if params == nil {
		return ""
	}
	var buf bytes.Buffer
	for i, p := range params.List {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString(renderFieldNames(p.Names))
		if len(p.Names) > 0 {
			buf.WriteString(" ")
		}
		buf.WriteString(exprToString(fset, p.Type, src))
	}
	return buf.String()
}

// renderFieldNames joins field names with ", ".
func renderFieldNames(names []*ast.Ident) string {
	var buf bytes.Buffer
	for j, n := range names {
		if j > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString(n.Name)
	}
	return buf.String()
}

// renderResults renders a FieldList of results as "int" or "(int, error)".
func renderResults(fset *token.FileSet, results *ast.FieldList, src []byte) string {
	if len(results.List) == 1 && len(results.List[0].Names) == 0 {
		return exprToString(fset, results.List[0].Type, src)
	}
	var buf bytes.Buffer
	buf.WriteString("(")
	for i, r := range results.List {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString(exprToString(fset, r.Type, src))
	}
	buf.WriteString(")")
	return buf.String()
}

// exprToString renders an AST expression as source text.
func exprToString(fset *token.FileSet, e ast.Expr, src []byte) string {
	start := fset.Position(e.Pos()).Offset
	end := fset.Position(e.End()).Offset
	if start < 0 || end > len(src) || start >= end {
		return ""
	}
	return string(src[start:end])
}

// insertAfterImports inserts text after the package clause and imports.
// fset is needed to convert token.Pos to byte offsets.
func insertAfterImports(fset *token.FileSet, f *ast.File, src []byte, text []byte) []byte {
	offset := importEndOffset(fset, f, src)
	out := make([]byte, 0, len(src)+len(text))
	out = append(out, src[:offset]...)
	out = append(out, text...)
	out = append(out, src[offset:]...)
	return out
}

// importEndOffset returns the byte offset after the last import,
// or after the package clause if there are no imports.
func importEndOffset(fset *token.FileSet, f *ast.File, src []byte) int {
	if pos := lastImportEnd(f, f.Imports); pos != 0 {
		return fset.Position(pos).Offset
	}
	return packageEndOffset(fset, f, src)
}

// lastImportEnd finds the end position of the GenDecl containing the last import.
func lastImportEnd(f *ast.File, imports []*ast.ImportSpec) token.Pos {
	if len(imports) == 0 {
		return 0
	}
	last := imports[len(imports)-1]
	for _, decl := range f.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}
		if genContainsImport(gen, last) {
			return gen.End()
		}
	}
	return 0
}

// genContainsImport reports whether gen declares the given import.
func genContainsImport(gen *ast.GenDecl, target *ast.ImportSpec) bool {
	for _, spec := range gen.Specs {
		if imp, ok := spec.(*ast.ImportSpec); ok && imp == target {
			return true
		}
	}
	return false
}

// packageEndOffset returns the offset after the package clause newline.
func packageEndOffset(fset *token.FileSet, f *ast.File, src []byte) int {
	offset := fset.Position(f.Name.End()).Offset
	for offset < len(src) && src[offset] != '\n' {
		offset++
	}
	return offset + 1
}


